[build]
    command = 'pnpm run build'
    functions = "functions"
    publish = "dist"

[[redirects]]
  from = "http://jardin-papillon.fr/*"
  to = "https://jardin-papillon.fr/:splat"
  status = 301
  force = true

[dev]
    targetPort = 4173

